export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const COUNT_TOTAL_AMOUNT = "COUNT_TOTAL_AMOUNT";
export const CLEAR_CART = "CLEAR_CART";

export const PLACE_ORDER = "PLACE_ORDER";
export const ERROR_IN_PLACE_ORDER = "ERROR_IN_PLACE_ORDER";
export const FETCH_ORDERS = "FETCH_ORDERS";
export const ERROR_IN_FETCH_ORDERS = "ERROR_IN_FETCH_ORDERS";
export const CANCEL_ORDER = "CANCEL_ORDER";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const ERROR_IN_ADD_PRODUCT = "ERROR_IN_ADD_PRODUCT";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const ERROR_IN_FETCH_PRODUCTS = "ERROR_IN_FETCH_PRODUCTS";
