export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const COUNT_TOTAL_AMOUNT = "COUNT_TOTAL_AMOUNT";
export const PLACE_ORDER = "PLACE_ORDER";
export const CANCEL_ORDER = "CANCEL_ORDER";
export const CLEAR_CART = "CLEAR_CART";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const ERROR_IN_ADD_PRODUCT = "ERROR_IN_ADD_PRODUCT";
